defmodule ExMidilib.AuGeneratorTest do
  use ExUnit.Case
  alias ExMidilib.AuGenerator

  test "generated file matches file generated by erlang version of this module" do
    # Derp no idea why this differs by the trivial amount in a few bytes, but it does
    expected_bytes = File.read!("test/files/au_120_0.5_1.au")
    assert AuGenerator.generate(120, 0.5, 1) == expected_bytes
  end
end
